# 11: front take 2; 12: put 2 
ninja_sima_main_node:
  ros__parameters:
    waypoints: [
                "TAKE_1_GO", "TAKE_1_DOCK",
                "PUT_1_GO",  "PUT_1_DOCK",
                "TAKE_2_GO", "TAKE_2_DOCK",
                "PUT_2_GO",  "PUT_2_DOCK",
                # "TAIL_2nd_FLOOR", "TAIL_2nd_FLOOR_GOAL",
                # "PUSH_1st_GROUP_WAIT", "PUSH_1st_GROUP_GO", "PUSH_1st_GROUP_DOWN",
                # "PUSH_2nd_GROUP_TRANSITION", "PUSH_2nd_GROUP_WAIT", "PUSH_2nd_GROUP_GO", "PUSH_2nd_GROUP_DOWN",
                ]
  
    TAKE_1_GO:
      x: 1.092
      y: 1.903
      yaw: 1.583
      task_type: "goto"
      task_num: "11"

    TAKE_1_DOCK:
      x: 1.114
      y: 1.852
      yaw: 1.591
      task_type: "docking"
      task_num: "11"

    PUT_1_GO:
      x: 0.730
      y: 1.887
      yaw: 0.012
      task_type: "go"
      task_num: "12"

    PUT_1_DOCK:
      x: 0.667
      y: 1.888
      yaw: 0.011
      task_type: "docking"
      task_num: "12"

    TAKE_2_GO:
      x: 1.215
      y: 1.786
      yaw: -3.102
      task_type: "goto"
      task_num: "11"
    
    TAKE_2_DOCK:
      x: 1.235
      y: 1.781
      yaw: -3.092
      task_type: "docking"
      task_num: "11"

    PUT_2_GO:
      x: 0.730
      y: 1.887
      yaw: 0.012
      task_type: "go"
      task_num: "12"

    PUT_2_DOCK:
      x: 0.667
      y: 1.888
      yaw: 0.011
      task_type: "docking"
      task_num: "12"

    TAIL_2nd_FLOOR:
      x: 0.700
      y: 1.811
      yaw: -0.456
      task_type: "docking"
      task_num: "42"

    TAIL_2nd_FLOOR_GOAL:
      x: 1.026
      y: 1.811
      yaw: -0.456
      task_type: "docking"
      task_num: "42"  

    PUSH_1st_GROUP_WAIT:
      x: 0.821
      y: 1.880
      yaw: -0.469
      task_type: "docking"
      task_num: "41" 

    PUSH_1st_GROUP_GO:
      x: 0.821
      y: 1.840
      yaw: -0.469
      task_type: "docking"
      task_num: "41"  

    PUSH_1st_GROUP_DOWN:
      x: 0.846
      y: 1.625
      yaw: -0.469
      task_type: "docking"
      task_num: "41"  

    PUSH_2nd_GROUP_TRANSITION:
      x: 0.821
      y: 1.880
      yaw: -0.469
      task_type: "docking"
      task_num: "41" 

    PUSH_2nd_GROUP_WAIT:
      x: 0.720
      y: 1.880
      yaw: -0.469
      task_type: "docking"
      task_num: "41" 

    PUSH_2nd_GROUP_GO:
      x: 0.720
      y: 1.840
      yaw: -0.481
      task_type: "docking"
      task_num: "41"  

    PUSH_2nd_GROUP_DOWN:
      x: 0.720
      y: 1.817
      yaw: -0.482
      task_type: "docking"
      task_num: "41"  
    

  