version: '3.8'

services:
  ninja-sima:
    build: .
    image: eurobot2026-ninja-sima-base:latest
    container_name: ninja-sima
    command: /bin/bash
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    stdin_open: true
    stop_grace_period: &STOP_GRACE_PERIOD 1s

    volumes:
      - ../NINJA-SIMA-ws:/home/user/NINJA-SIMA-ws
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/user/.Xauthority
      - /dev:/dev
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

    working_dir:
      /home/user/NINJA-SIMA-ws

    environment:
      - DISPLAY=${DISPLAY}  # Set display environment variable
      - RCUTILS_COLORIZED_OUTPUT=1
      - XAUTHORITY=/home/user/.Xauthority   # Set Xauthority path
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=59  # ! Please distinguish the domain ID with other containers
      # - CYCLONEDDS_URI=file:///home/user/cyclonedds.xml

  uros-agent:
    build:
      dockerfile: Dockerfile.uros_agent
    image: eurobot2026-uros-agent:latest
    container_name: uros-agent
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    stdin_open: true
    stop_grace_period: &STOP_GRACE_PERIOD 1s

    volumes:
      - /dev:/dev

    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - AGENT_TYPE=${AGENT_TYPE:-serial}
      - AGENT_BAUD_RATE=${AGENT_BAUD_RATE:-1000000}
      - AGENT_DEVICE=${AGENT_DEVICE:-/dev/ttyAMA0}

    entrypoint: ["/bin/bash", "-c", "/root/uros-agent-ws/uros-agent-start.sh"]
    command: ["/bin/bash"]
